# Generated by Django 5.1.3 on 2025-09-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='semi_major_axis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
