# Generated by Django 5.1.3 on 2025-09-25 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_planet_semi_major_axis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ra', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('star_temp', models.FloatField(blank=True, null=True)),
                ('star_radius', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='api.star'),
        ),
    ]
