# Generated by Django 5.1.3 on 2025-09-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_star_planet_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='sy_dist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
