# Generated by Django 5.1.3 on 2025-10-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_star_sy_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='user_inputted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='star',
            name='user_inputted',
            field=models.BooleanField(default=False),
        ),
    ]
