# Generated by Django 4.2 on 2025-10-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_planet_user_inputted_star_user_inputted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
